# Q learning

In [1]:
import numpy as np
import gym
import gridworld
from gym import wrappers, logger

import matplotlib
import matplotlib.pyplot as plt

%matplotlib inline
%load_ext autoreload
%autoreload 2

In [57]:
env = gym.make('CartPole-v1')
outdir = 'cartpole-v0/random-agent-results'
envm = wrappers.Monitor(env, directory=outdir, force=True, video_callable=False)
env.seed(0)

[0]

In [16]:
import torch

class NN(torch.nn.Module):
    """ simple Neural Net """
    def __init__(self, inSize, outSize, layers=[]):
        super(NN, self).__init__()
        self.layers = torch.nn.ModuleList([])
        for x in layers:
            self.layers.append(torch.nn.Linear(inSize, x))
            inSize = x
        self.layers.append(torch.nn.Linear(inSize, outSize))

    def forward(self, x):
        x = self.layers[0](x)
        for i in range(1, len(self.layers)):
            x = torch.nn.functional.leaky_relu(x)
            x = self.layers[i](x)
        return x

In [59]:
obs.reshape(1, -1)

array([[ 0.00175771,  0.04038352, -0.00908715, -0.00983419]],
      dtype=float32)

In [58]:
Q = NN(4, 2, layers=[16])

obs1 = envm.reset().astype("float32")
obs2 = obs1 + 2

x = torch.from_numpy(np.array([obs1, obs2]))

with torch.no_grad():
    kelbay = Q(x)
    torch.argmax(kelbay).item()

In [37]:
envm.step(1)

(array([ 0.00256538,  0.23563461, -0.00928383, -0.30537031]), 1.0, False, {})

In [38]:
from collections import deque

In [45]:
prout = deque(maxlen=4)

In [48]:
prout.append("zizi")
prout.append("caca")
prout.append("fesse")
prout.append("pipi")

In [60]:
kelbay

tensor([[ 0.1021,  0.0581],
        [ 0.9158, -0.3509]])

In [69]:
ids = torch.Tensor([0, 1]).long()
caca = kelbay.gather(1, ids.view(-1,1))

In [63]:
caca

tensor([[ 0.1021],
        [-0.3509]])

In [66]:
caca.reshape(1, -1).squeeze()

tensor([ 0.1021, -0.3509])